app:
  base-url: http://localhost:9000
  jwt-token-key: fipjwepgihowrjgpieongiwrjgglihngukhwnipgo
spring:
  jmx:
    default-domain: com.a6raywa1cher.javahackbugslimited
    unique-names: true
spring.mail.host: smtp.yandex.ru
spring.mail.port: 465
spring.mail.username: noreply@a6raywa1cher.com
spring.mail.password: ----
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true
server.port: 8081
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:postgresql://localhost:5433/javahack-bugs-limited
spring.datasource.username: postgres
spring.datasource.password: postgres
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false